import type { Metadata } from "next";
import { IBM_Plex_Mono, Inter } from "next/font/google";
import { GoogleAnalytics } from "@next/third-parties/google";
import "./globals.css";

const IBMPlexMono = IBM_Plex_Mono({
  preload: true,
  weight: ["500"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Home | Hacknest — Imagine a Community",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={IBMPlexMono.className}>{children}</body>
      <GoogleAnalytics
        gaId={process.env.NEXT_PUBLIC_GA_ID || "GA-XXXXXXXXX "}
      />
    </html>
  );
}
